# action.yaml
name: 'Azure Managed CCF Add Member action'
author: 'Microsoft'
description: 'Ac action to add a member to a CCF network and activate it.'
branding: 
  icon: 'package'
  color: 'blue'
runs:
  using: 'docker'
  image: 'Dockerfile'
